### PR TITLE
Make Python3 Compatible

### PR DESCRIPTION
**Pull request by nickmflorin**
Mostly has to do with changing the `print` statement to `print()`, but also a few `xrange`(s) to `range`.  Cleaned up the Flake8 errors and what not because it was confusing as hell to follow.

### CODE REVIEW

**Comment by fdintino** [comment]
Would it not be more sensible to rebase our two commits onto the latest master branch of upstream?

**Comment by fdintino** [comment]
I am referring to 6e85f53 and 2c4e96c. Plus a commit to update setup.cfg with a new version suffix

**Comment by nickmflorin** [comment]
@fdintino when you say master branch of upstream, I assume you mean the original repository we forked off of?  Chris & I talked about that and we weren't sure why David didn't mention that (or if he did I missed it).  I'm not familiar with working with forks that much so whatever you think I'm fine with - I don't mind rebasing it.

**Comment by nickmflorin** [comment]
Oh nvm you mean rebasing it off of our master branch

**Comment by fdintino** [comment]
No I meant the original repository’s master branch. Ideally we should open a PR at some point with our changes so we can avoid using a fork. But until then it would be good to be rebased off of a relatively recent commit.

**Comment by nickmflorin** [comment]
Gotcha, yeah no problem I can do that.  I think in their master branch they made a lot of changes to these files because of how badly they were written so it should eliminate a lot of the red/green

**Comment by fdintino** [comment]
Yes, given that the upstream polymorphic is already python 3 compatible, it shouldn’t need any changes at all for that.

**Pull request closed without merging**
